// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkasxlqotqktlemcoiwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYXN4bHFvdHFrdGxlbWNvaXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODE3NzYsImV4cCI6MjA3MjA1Nzc3Nn0.3rkOKYlv-xVXmbQR_gObXlaqL3Wp4TDQFENTACbouaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});